name: safe-bridge-backend CI/CD

on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Determine image tag
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "CONTAINER_NAME=safe-bridge-backend" >> $GITHUB_OUTPUT
          else
            echo "TAG=dev" >> $GITHUB_OUTPUT
            echo "CONTAINER_NAME=safe-bridge-test" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t bingle625/gdg-cau-team5-backend:$TAG --push .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          TAG: ${{ steps.set-tag.outputs.tag }}
          CONTAINER_NAME: ${{ steps.set-tag.outputs.container_name }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying container: $CONTAINER_NAME with tag: $TAG"
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/gdg-cau-team5-backend:$TAG

            if [[ "$TAG" == "latest" ]]; then
              docker run -d --name safe-bridge-backend -p 8080:8080 bingle625/gdg-cau-team5-backend:latest
            else
              docker run -d --name safe-bridge-test -p 8081:8080 bingle625/gdg-cau-team5-backend:dev
            fi
